# Servidor
server.port=8080

# Rutas usando las variables de tu docker-compose
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/auth/**

# Orden corregido para apuntes y materias usando tus variables
spring.cloud.gateway.server.webflux.routes[1].id=apunte-service
spring.cloud.gateway.server.webflux.routes[1].uri=${APUNTE_SERVICE_URL}
# OJO AQUI: Cambiamos el ** del medio por un solo *
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/materias/*/apuntes/**

spring.cloud.gateway.server.webflux.routes[2].id=materia-service
spring.cloud.gateway.server.webflux.routes[2].uri=${MATERIA_SERVICE_URL}
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/materias/**

# JWT
jwt.secret=${JWT_SECRET}